# version: '3.8'
# services:
#     database:
#         image: "postgres"
#         container_name: db
#         env_file:
#             - .env.postgres
#         volumes:
#             - database-data:/var/lib/postgresql/data/
#         ports:
#             - "5432:5432"
#     api:
#         container_name: api
#         restart: always
#         build:
#           context: .
#           dockerfile: ./dockerfile/Dockerfile.api
#         environment:
#             - PORT=4000
#         ports:
#             - "4000:4000"
#         links:
#             - database
#         volumes:
#             - ./matinka-calendar-api/src:/usr/src/app/src

#     react:
#         container_name: react
#         build:
#           context: .
#           dockerfile: ./dockerfile/Dockerfile.react
#         volumes:
#             - ./matinka-calendar-react/src:/app/src
#             - ./matinka-calendar-react/public:/app/public
#             - ./matinka-calendar-react/assets:/app/assets
#         ports:
#             - "3000:3000"
#         stdin_open: true
#         environment:
#           - CHOKIDAR_USEPOLLING=true
# volumes:
#     database-data:
